language: go

go:
  - 1.12
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make test
  - make build

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: ddns-*
  skip_cleanup: true
  on:
    tags: true
